# pyproject.toml — aaf2resolve-spec
# Central config for ruff, mypy, pytest, and black (format check).
# CI runs: ruff → black --check → mypy → pytest

[tool.ruff]
target-version = "py311"
line-length = 100
exclude = [
  ".git",
  ".github",
  ".devcontainer",
  "docs",
  "reports",
  "build",
  "dist",
]

[tool.ruff.lint]
# Rules we actively enforce
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort import order
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
]

# Temporary ignores so CI passes during scaffolding
ignore = [
  "E203", # black slice spacing
  "E501", # line too long
  "UP006",# typing.Dict→dict
  "UP035",# deprecated typing imports
  "UP037",# quoted annotations
  "UP045",# Optional[X]→X|None
  "UP009",# unnecessary coding comment
  "UP015",# unnecessary open() mode
]

[tool.ruff.lint.isort]
known-first-party = ["aaf2resolve_spec", "src"]
combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # allow re-exports

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.mypy]
ignore_errors = true
files = ["src", "tests"]
ignore_missing_imports = true
disallow_untyped_defs = false
