name: CI (handoff + validation + lint)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          # Improves cache hits:
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
            pyproject.toml
            setup.cfg
            setup.py

      - name: Install dev deps
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install black ruff mypy pytest PyYAML

      - name: Lint (ruff) & format check (black)
        run: |
          ruff check --output-format=github .
          black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Unit tests (pytest)
        run: |
          mkdir -p test-artifacts
          pytest -q --maxfail=1 --disable-warnings \
            --junitxml=test-artifacts/pytest-junit.xml 2>&1 | tee test-artifacts/pytest.log
        continue-on-error: false

      - name: Validate handoff.yml (required keys)
        if: hashFiles('handoff/handoff.yml') != ''
        run: |
          python - <<'PY'
          import sys, y
