name: CI (handoff + validation + lint)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install black ruff

      - name: Lint & format (ruff + black --check)
        run: |
          ruff check .
          black --check .

      - name: Validate handoff.yml (required keys)
        run: |
          python - <<'PY'
          import sys, yaml
          req = {"owner","status","artifacts","outputs_expected","acceptance_criteria","next_action"}
          data = yaml.safe_load(open("handoff/handoff.yml","r", encoding="utf-8"))
          if not isinstance(data, dict):
              print("handoff.yml must be a mapping"); sys.exit(1)
          missing = sorted(req - set(data))
          if missing:
              print("Missing keys:", ", ".join(missing)); sys.exit(1)
          print("handoff.yml OK")
          PY

      - name: Schema smoke test (validator + minimal example)
        run: |
          python -m src.validate_canonical tests/samples/minimal_valid.json --verbose
